public_key = b'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILFPQeUmSdc9JyA0xAzh2iriV4njIbI8EYG1c2VpYUK1'
private_key = b"""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCxT0HlJknXPScgNMQM4doq4leJ4yGyPBGBtXNlaWFCtQAAAJh64bC3euGw
twAAAAtzc2gtZWQyNTUxOQAAACCxT0HlJknXPScgNMQM4doq4leJ4yGyPBGBtXNlaWFCtQ
AAAEDkqygDl+HsGtr/taNxQoZFvfMzNZ95jVHBmYTjqP6jqrFPQeUmSdc9JyA0xAzh2iri
V4njIbI8EYG1c2VpYUK1AAAAE2Nhc3BlQEhhcmJvZS1LYXNzZW4BAg==
-----END OPENSSH PRIVATE KEY-----"""